AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudWatch Cross-Account Lambda Function - SOURCE Account Setup'

Parameters:
  TargetAccountId:
    Type: String
    Description: AWS Account ID where CloudWatch data resides
    AllowedPattern: '[0-9]{12}'
    ConstraintDescription: Must be a valid 12-digit AWS account ID
  
  TargetRegion:
    Type: String
    Description: AWS Region where CloudWatch data resides
    Default: us-east-1
    AllowedValues:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - eu-west-1
      - eu-central-1
      - ap-south-1
      - ap-southeast-1
      - ap-southeast-2
      - ap-northeast-1

Resources:
  # IAM Role for Lambda Execution
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CloudWatchLambdaExecutionRole
      Description: Execution role for cross-account CloudWatch Lambda
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: CrossAccountAssumeRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: sts:AssumeRole
                Resource: !Sub 'arn:aws:iam::${TargetAccountId}:role/CrossAccountCloudWatchRole'

  # Lambda Function
  CloudWatchFetcherFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: CloudWatchCrossAccountFetcher
      Description: Fetches CloudWatch metrics from cross-account
      Runtime: python3.11
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 60
      MemorySize: 256
      Environment:
        Variables:
          TARGET_ACCOUNT_ROLE_ARN: !Sub 'arn:aws:iam::${TargetAccountId}:role/CrossAccountCloudWatchRole'
          TARGET_REGION: !Ref TargetRegion
      Code:
        ZipFile: |
          import json
          import os
          import boto3
          from datetime import datetime, timedelta
          from botocore.exceptions import ClientError


          def lambda_handler(event, context):
              """
              Lambda function to fetch CloudWatch metrics from a different AWS account.
              """
              
              target_role_arn = os.environ.get('TARGET_ACCOUNT_ROLE_ARN')
              target_region = os.environ.get('TARGET_REGION', 'us-east-1')
              
              if not target_role_arn:
                  return {
                      'statusCode': 400,
                      'body': json.dumps({
                          'error': 'TARGET_ACCOUNT_ROLE_ARN environment variable is required'
                      })
                  }
              
              try:
                  credentials = assume_cross_account_role(target_role_arn)
                  
                  cloudwatch_client = boto3.client(
                      'cloudwatch',
                      region_name=target_region,
                      aws_access_key_id=credentials['AccessKeyId'],
                      aws_secret_access_key=credentials['SecretAccessKey'],
                      aws_session_token=credentials['SessionToken']
                  )
                  
                  metrics_data = fetch_cloudwatch_metrics(cloudwatch_client, event)
                  
                  return {
                      'statusCode': 200,
                      'body': json.dumps({
                          'message': 'Successfully fetched CloudWatch data',
                          'data': metrics_data
                      }, default=str)
                  }
                  
              except ClientError as e:
                  error_code = e.response['Error']['Code']
                  error_message = e.response['Error']['Message']
                  
                  return {
                      'statusCode': 500,
                      'body': json.dumps({
                          'error': f'{error_code}: {error_message}'
                      })
                  }
              except Exception as e:
                  return {
                      'statusCode': 500,
                      'body': json.dumps({
                          'error': str(e)
                      })
                  }


          def assume_cross_account_role(role_arn, session_name='CrossAccountCloudWatchSession'):
              sts_client = boto3.client('sts')
              
              response = sts_client.assume_role(
                  RoleArn=role_arn,
                  RoleSessionName=session_name,
                  DurationSeconds=3600
              )
              
              return response['Credentials']


          def fetch_cloudwatch_metrics(cloudwatch_client, event):
              namespace = event.get('namespace', 'AWS/EC2')
              metric_name = event.get('metric_name', 'CPUUtilization')
              dimensions = event.get('dimensions', [])
              statistics = event.get('statistics', ['Average', 'Maximum'])
              period = event.get('period', 300)
              
              end_time = datetime.utcnow()
              start_time = end_time - timedelta(hours=event.get('hours_back', 1))
              
              metric_params = {
                  'Namespace': namespace,
                  'MetricName': metric_name,
                  'StartTime': start_time,
                  'EndTime': end_time,
                  'Period': period,
                  'Statistics': statistics
              }
              
              if dimensions:
                  metric_params['Dimensions'] = dimensions
              
              response = cloudwatch_client.get_metric_statistics(**metric_params)
              
              available_metrics = cloudwatch_client.list_metrics(
                  Namespace=namespace,
                  MetricName=metric_name
              )
              
              return {
                  'metric_statistics': response.get('Datapoints', []),
                  'metric_label': response.get('Label', ''),
                  'available_metrics': available_metrics.get('Metrics', [])[:10]
              }

Outputs:
  LambdaFunctionName:
    Description: Name of the Lambda function
    Value: !Ref CloudWatchFetcherFunction
    Export:
      Name: CloudWatchCrossAccountFetcherName
  
  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt CloudWatchFetcherFunction.Arn
    Export:
      Name: CloudWatchCrossAccountFetcherArn
  
  LambdaExecutionRoleArn:
    Description: ARN of the Lambda execution role (needed for target account trust policy)
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
      Name: CloudWatchLambdaExecutionRoleArn
  
  TargetAccountRoleArn:
    Description: ARN of the role that needs to be created in target account
    Value: !Sub 'arn:aws:iam::${TargetAccountId}:role/CrossAccountCloudWatchRole'
  
  NextSteps:
    Description: Instructions for target account setup
    Value: !Sub |
      Create role 'CrossAccountCloudWatchRole' in account ${TargetAccountId}
      with trust policy allowing ${LambdaExecutionRole.Arn} to assume it.
      See cloudformation_target_account.yaml for template.


